version: "3.2"

services:
  tinydns:
    ports:
      - target: "53"
        published: "53"
        protocol: "tcp"
      - target: "53"
        published: "53"
        protocol: "udp"
  consul:
    ports:
      - target: "8500"
        published: "8500"
        protocol: "tcp"
  mysql:
    ports:
      - target: "3306"
        published: "3306"
        protocol: "tcp"
